# Numpy 연산

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2],[3,4]])
B=np.array([[3,1],[1,6]])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [5]:
# 요소 연산
print(A+B)
print(A*B)

[[ 4  3]
 [ 4 10]]
[[ 3  2]
 [ 3 24]]


In [12]:
# 브로드캐스트
C=10
print(A+C)
print(A*C)

[[11 12]
 [13 14]]
[[10 20]
 [30 40]]


In [14]:
D=np.array([10,20])
print(A+D)

[[11 22]
 [13 24]]


In [15]:
# 내적
print(np.dot(A,B))

[[ 5 13]
 [13 27]]


In [22]:
# A : 2X2
# C : 스칼라 연산
np.dot(A,C)

array([[10, 20],
       [30, 40]])

In [17]:
E=np.array([[1,2],[3,4],[5,6]])
E

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# A : 2X2
# E : 3X2
np.dot(A,E)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

## AND 게이트

In [28]:
def AND(x1,x2):
    w1,w2,theta=1,1,1.5
    tmp=x1*w1+x2*w2
    
    if tmp <= theta :
        return 0
    elif tmp > theta :
        return 1

In [33]:
print('AND(0,0) : ',AND(0,0))
print('AND(0,1) : ',AND(0,1))
print('AND(1,0) : ',AND(1,0))
print('AND(1,1) : ',AND(1,1))

AND(0,0) :  0
AND(0,1) :  0
AND(1,0) :  0
AND(1,1) :  1


## NAND 게이트

In [36]:
def NAND(x1,x2):
    w1,w2,theta=1,1,1.5
    tmp=x1*w1+x2*w2
    
    if tmp <= theta :
        return 1
    elif tmp > theta :
        return 0

In [37]:
print('NAND(0,0) : ',NAND(0,0))
print('NAND(0,1) : ',NAND(0,1))
print('NAND(1,0) : ',NAND(1,0))
print('NAND(1,1) : ',NAND(1,1))

NAND(0,0) :  1
NAND(0,1) :  1
NAND(1,0) :  1
NAND(1,1) :  0


## OR 게이트

In [40]:
def OR(x1,x2):
    w1,w2,theta=1,1,0.5
    tmp=x1*w1+x2*w2
    
    if tmp <= theta :
        return 0
    elif tmp > theta :
        return 1

In [41]:
print('OR(0,0) : ',OR(0,0))
print('OR(0,1) : ',OR(0,1))
print('OR(1,0) : ',OR(1,0))
print('OR(1,1) : ',OR(1,1))

OR(0,0) :  0
OR(0,1) :  1
OR(1,0) :  1
OR(1,1) :  1
