# Numpy 연산

In [2]:
import numpy as np

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[3,1],[1,6]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
# 요소 연산
print(A+B)
print(A*B)

[[ 4  3]
 [ 4 10]]
[[ 3  2]
 [ 3 24]]


In [ ]:
# 브로드캐스트
C=10
print(A+C)
print(A*C)

[[11 12]
 [13 14]]
[[10 20]
 [30 40]]


In [ ]:
D=np.array([10,20])
print(A+D)

[[11 22]
 [13 24]]


In [ ]:
# 내적
print(np.dot(A,B))

[[ 5 13]
 [13 27]]


In [ ]:
# A : 2X2
# C : 스칼라 연산
np.dot(A,C)

array([[10, 20],
       [30, 40]])

In [ ]:
E=np.array([[1,2],[3,4],[5,6]])
E

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# A : 2X2
# E : 3X2
np.dot(A,E)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

## AND 게이트

In [ ]:
def AND(x1,x2):
    w1,w2,theta=1,1,1.5
    tmp=x1*w1+x2*w2
    
    if tmp <= theta :
        return 0
    elif tmp > theta :
        return 1

In [ ]:
print('AND(0,0) : ',AND(0,0))
print('AND(0,1) : ',AND(0,1))
print('AND(1,0) : ',AND(1,0))
print('AND(1,1) : ',AND(1,1))

AND(0,0) :  0
AND(0,1) :  0
AND(1,0) :  0
AND(1,1) :  1


## NAND 게이트

In [ ]:
def NAND(x1,x2):
    w1,w2,theta=1,1,1.5
    tmp=x1*w1+x2*w2
    
    if tmp <= theta :
        return 1
    elif tmp > theta :
        return 0

In [ ]:
print('NAND(0,0) : ',NAND(0,0))
print('NAND(0,1) : ',NAND(0,1))
print('NAND(1,0) : ',NAND(1,0))
print('NAND(1,1) : ',NAND(1,1))

NAND(0,0) :  1
NAND(0,1) :  1
NAND(1,0) :  1
NAND(1,1) :  0


## OR 게이트

In [ ]:
def OR(x1,x2):
    w1,w2,theta=1,1,0.5
    tmp=x1*w1+x2*w2
    
    if tmp <= theta :
        return 0
    elif tmp > theta :
        return 1

In [ ]:
print('OR(0,0) : ',OR(0,0))
print('OR(0,1) : ',OR(0,1))
print('OR(1,0) : ',OR(1,0))
print('OR(1,1) : ',OR(1,1))

OR(0,0) :  0
OR(0,1) :  1
OR(1,0) :  1
OR(1,1) :  1


In [6]:
def AND(x1,x2):
    w1,w2,theta=1,1,1.5

    x=np.array([x1,x2])
    w=np.array([w1,w2])
    b=-theta

    tmp=np.sum(w*x)+b
    
    if tmp <= 0 :
        return 0
    elif tmp > 0 :
        return 1

def NAND(x1,x2):
    w1,w2,theta=1,1,1.5

    x=np.array([x1,x2])
    w=np.array([w1,w2])
    b=-theta

    tmp=np.sum(w*x)+b
    
    if tmp <= 0 :
        return 1
    elif tmp > 0 :
        return 0

def OR(x1,x2):
    w1,w2,theta=1,1,0.5
    
    x=np.array([x1,x2])
    w=np.array([w1,w2])
    b=-theta

    tmp=np.sum(w*x)+b
    
    if tmp <= 0 :
        return 0
    elif tmp > 0 :
        return 1

In [7]:
print('AND(0,0) : ',AND(0,0))
print('AND(0,1) : ',AND(0,1))
print('AND(1,0) : ',AND(1,0))
print('AND(1,1) : ',AND(1,1))

print('NAND(0,0) : ',NAND(0,0))
print('NAND(0,1) : ',NAND(0,1))
print('NAND(1,0) : ',NAND(1,0))
print('NAND(1,1) : ',NAND(1,1))

print('OR(0,0) : ',OR(0,0))
print('OR(0,1) : ',OR(0,1))
print('OR(1,0) : ',OR(1,0))
print('OR(1,1) : ',OR(1,1))

AND(0,0) :  0
AND(0,1) :  0
AND(1,0) :  0
AND(1,1) :  1
NAND(0,0) :  1
NAND(0,1) :  1
NAND(1,0) :  1
NAND(1,1) :  0
OR(0,0) :  0
OR(0,1) :  1
OR(1,0) :  1
OR(1,1) :  1


## XOR게이트

In [12]:
def XOR(x1,x2):
    s1,s2=NAND(x1,x2),OR(x1,x2)

    return AND(s1,s2)

In [13]:
print('XOR(0,0) : ',XOR(0,0))
print('XOR(0,1) : ',XOR(0,1))
print('XOR(1,0) : ',XOR(1,0))
print('XOR(1,1) : ',XOR(1,1))

XOR(0,0) :  0
XOR(0,1) :  1
XOR(1,0) :  1
XOR(1,1) :  0


# 활성화 함수 구현하기

In [14]:
import numpy as np

## Step Function 

In [16]:
def step_function(x):
    if x>0:
        return 1
    else:
        return 0

In [17]:
step_function(3)

1

어떤 값이 입력되어도 0 or 1 반환

In [18]:
# numpy 활용한 Step Function
x=np.array([-1.0,5.0,2.0])

In [19]:
y=x>0
y

array([False,  True,  True])

In [20]:
y.astype(np.int64)

array([0, 1, 1])

In [21]:
def step_function(x):
    y=x>0
    return y.astype(np.int64)

In [22]:
x=np.array([-1.0,5.0,2.0])
step_function(x)

array([0, 1, 1])

## Sigmoid 활성화 함수

In [23]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [25]:
x=np.array([-1.0,5.0,2.0])
sigmoid(x)

array([0.26894142, 0.99330715, 0.88079708])

## ReLU 활성화 함수

In [28]:
def relu(x):
    return np.maximum(0,x)

In [29]:
x=np.array([-1.0,5.0,2.0])
relu(x)

array([0., 5., 2.])

# 3층 신경망 구현하기

In [34]:
# Sample
import numpy as np
X=np.array([1,2]) # x1, x2
W=np.array([[1,3,5],[2,4,6]])
B=np.array([1,1,1])

Y=np.dot(X,W)+B

In [35]:
Y

array([ 6, 12, 18])

In [40]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

## 1층

In [39]:
# 105p
X1=np.array([1.0,0.5]) # 1x2
W1=np.array([[0.1,0.3,0.5],
             [0.2,0.4,0.6]]) # 2x3
B1=np.array([0.1,0.2,0.3]) # 1x3

A1=np.dot(X1,W1)+B1
A1

array([0.3, 0.7, 1.1])

In [42]:
Z1=sigmoid(A1)
Z1 # 1x3

array([0.57444252, 0.66818777, 0.75026011])

## 2층

In [46]:
W2=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]]) # 3x2
B2=np.array([.1,.2]) # 1x2

A2=np.dot(Z1,W2)+B2
A2

array([0.51615984, 1.21402696])

In [48]:
Z2=sigmoid(A2)
Z2

array([0.62624937, 0.7710107 ])

## 출력층

In [50]:
W3=np.array([[0.1,0.3],[0.2,0.4]])
B3=np.array([.1,.2])

A3=np.dot(Z2,W3)+B3
A3

array([0.31682708, 0.69627909])

In [51]:
# 항등함수
def identity_function(x):
    return x

In [52]:
Y=identity_function(A3)
Y

array([0.31682708, 0.69627909])

## 합치기

In [53]:
# 입력층 X
# W,B
# 활성화 함수

In [54]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [55]:
def identity_function(x):
    return x

In [56]:
def init_network():
    network={}

    network['W1']=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1']=np.array([0.1,0.2,0.3])

    network['W2']=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2']=np.array([.1,.2])

    network['W3']=np.array([[0.1,0.3],[0.2,0.4]])
    network['b3']=np.array([.1,.2])

    return network

In [59]:
def forward(network, x):
    W1,W2,W3=network['W1'],network['W2'],network['W3']
    b1,b2,b3=network['b1'],network['b2'],network['b3']

    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)

    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)

    a3=np.dot(z2,W3)+B3
    y=identity_function(a3)

    return y

In [65]:
network=init_network()
X=np.array([1.0,0.5])
y=forward(network,X)

In [66]:
y

array([0.31682708, 0.69627909])

# 소프트맥스 구현하기

In [67]:
a=np.array([0.3,2.9,4.0])

In [68]:
def softmax(x):
    exp_x=np.exp(x)
    sum_exp_x=np.sum(exp_x)
    y=exp_x/sum_exp_x

    return y

$softmax(x)=\frac{\exp{(x)}}{\sum{exp{(x)}}}$

In [69]:
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

In [70]:
np.sum(softmax(a))

1.0

In [71]:
a=np.array([1010,1000,990])
softmax(a)

<ipython-input-68-d0bcd4801fd0>:2: RuntimeWarning: overflow encountered in exp
  exp_x=np.exp(x)
<ipython-input-68-d0bcd4801fd0>:4: RuntimeWarning: invalid value encountered in true_divide
  y=exp_x/sum_exp_x


array([nan, nan, nan])

Overflow

In [72]:
def softmax(x):
    c=np.max(x)
    exp_x=np.exp(x-c)
    sum_exp_x=np.sum(exp_x)
    y=exp_x/sum_exp_x

    return y

$softmax(x)=\frac{\exp{(x)}/\exp{c}}{\sum{exp{(x)}/\exp{c}}}$

In [73]:
a=np.array([1010,1000,990])
softmax(a)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [74]:
np.sum(softmax(a))

1.0